### ISSUE TITLE
Redmine 5-0 branch - Zeitwerk issues

### ISSUE THREAD

**Issue by popy2k14** [JGallot/redmine_workflow_enhancements#1]
Dear @JGallot ,

Thx for your efforts bringing this to redmine 5.
I tried your redmine-5.0 branch but it does not work on redmine 5.0.5.

I think the issue is the different loading on the zeitwerk framework.
Here is a log from "uninstalling" the plugin (sadly dont have it from installing, but it's nearly the same):

```
chef@pasarbticket00:/opt/redmine$ bundle exec rake redmine:plugins NAME=redmine_workflow_enhancements  RAILS_ENV=production VERSION=0
Rails Error: Unable to access log file. Please ensure that /opt/redmine/log/production.log exists and is writable (ie, make it writable for user and group: chmod 0664 /opt/redmine/log/production.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
Creating scope :sorted. Overwriting existing method User.sorted.
Creating scope :sorted. Overwriting existing method Group.sorted.
Creating scope :system. Overwriting existing method Enumeration.system.
rake aborted!
LoadError: cannot load such file -- workflow_enhancements/hooks
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies/zeitwerk_integration.rb:51:in `require_dependency'
/opt/redmine/plugins/redmine_workflow_enhancements/init.rb:1:in `<top (required)>'
/opt/redmine/lib/redmine/plugin_loader.rb:31:in `load'
/opt/redmine/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/opt/redmine/lib/redmine/plugin_loader.rb:108:in `each'
/opt/redmine/lib/redmine/plugin_loader.rb:108:in `block in load'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:427:in `instance_exec'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:603:in `catch'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:199:in `block in halting'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:512:in `each'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:512:in `invoke_before'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/callbacks.rb:105:in `run_callbacks'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/reloader.rb:88:in `prepare!'
/var/lib/gems/3.0.0/gems/railties-6.1.7.2/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
/var/lib/gems/3.0.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:32:in `instance_exec'
/var/lib/gems/3.0.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:32:in `run'
/var/lib/gems/3.0.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/var/lib/gems/3.0.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:60:in `run_initializers'
/var/lib/gems/3.0.0/gems/railties-6.1.7.2/lib/rails/application.rb:391:in `initialize!'
/opt/redmine/config/environment.rb:16:in `<top (required)>'
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
/var/lib/gems/3.0.0/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:332:in `block in require'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:299:in `load_dependency'
/var/lib/gems/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:332:in `require'
/var/lib/gems/3.0.0/gems/railties-6.1.7.2/lib/rails/application.rb:367:in `require_environment!'
/var/lib/gems/3.0.0/gems/railties-6.1.7.2/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/opt/redmine/lib/tasks/redmine.rake:73:in `block (2 levels) in <top (required)>'
/usr/share/rubygems-integration/all/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
chef@pasarbticket00:/opt/redmine$
```

Already tried to change the dependencies of the hooks and patches, but then it also does'nt run.
Passenger error on restarting redmine.

Any hint's how to change the plugin to make it work with redmine 5.x?

thx

**Comment by popy2k14** [comment]
I have got it semi working here for redmine 5.0.5:  https://github.com/popy2k14/redmine_workflow_enhancements/tree/redmine-5.0_without_workspace

**Comment by JGallot** [comment]
HI,
I'll give a look this summmer.
thx

**Comment by popy2k14** [comment]
thx, take your time
